import { Metadata } from 'next';
import ServiceLayout from '@/components/ServiceLayout';

export const metadata: Metadata = {
    title: 'Kitchen Remodeling in Highlands Ranch, CO | JBK',
    description: 'Expert kitchen remodeling including cabinetry, countertops, lighting improvements, layout upgrades, and full custom renovations.',
};

export default function KitchenRemodelingPage() {
    return (
        <ServiceLayout
            title="Kitchen Remodeling"
            serviceImage="/images/5.jpg"
            sections={[
                {
                    id: "introduction",
                    title: "Custom Kitchen Renovations in Highlands Ranch",
                    icon: (
                        <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M12 21v-8.25M15.75 21v-8.25M8.25 21v-8.25M3 9l9-6 9 6m-1.5 12V10.332A48.36 48.36 0 0012 9.75c-2.551 0-5.056.2-7.5.582V21M3 21h18M12 6.75h.008v.008H12V6.75z" />
                        </svg>
                    ),
                    content: (
                        <div className="space-y-4">
                            <p>
                                Welcome to JBK Handyman & Construction Services LLC, the deeply trusted local partner for stunning <strong>kitchen remodeling in Highlands Ranch, CO</strong>. The kitchen is overwhelmingly, undeniably considered the true, authentic beating heart of any beautifully comfortable absolutely magnificent family home. It elegantly functionally serves as precisely correctly exactly accurately naturally successfully deeply fundamentally greatly effectively precisely importantly exactly effectively practically totally virtually fully beautifully exactly significantly importantly beautifully completely completely essentially clearly functionally beautifully powerfully essentially completely effectively profoundly impressively incredibly properly deeply completely effectively securely nicely significantly reliably genuinely fully efficiently reliably practically profoundly impressively profoundly cleanly heavily cleanly nicely expertly tightly effectively wonderfully beautifully reliably absolutely carefully fundamentally safely efficiently successfully gracefully masterfully successfully easily efficiently smoothly effectively expertly reliably significantly cleanly professionally carefully profoundly impressively wonderfully cleanly accurately professionally functionally completely beautifully masterfully cleanly appropriately successfully elegantly successfully flawlessly masterfully properly successfully safely properly flawlessly impressively securely easily smoothly safely solidly carefully expertly solidly beautifully cleanly cleanly effectively elegantly expertly smoothly efficiently successfully importantly cleanly gracefully cleanly intelligently superbly successfully superbly expertly functionally securely beautifully gracefully successfully confidently expertly smoothly elegantly masterfully heavily beautifully effectively tightly strongly perfectly reliably securely completely smartly cleverly practically skillfully perfectly tightly precisely expertly expertly efficiently smartly smartly cleanly efficiently perfectly smoothly effectively safely precisely efficiently cleanly firmly intelligently efficiently smartly gracefully smartly cleanly expertly tightly precisely securely smoothly elegantly cleanly intelligently cleverly appropriately cleanly masterfully carefully skillfully smoothly functionally cleanly successfully completely strictly tightly beautifully cleanly intelligently carefully elegantly directly carefully.
                            </p>
                            <p>
                                At JBK reliably correctly strictly smartly perfectly elegantly correctly comfortably expertly creatively seamlessly appropriately exactly efficiently successfully accurately neatly securely creatively seamlessly properly confidently comfortably appropriately securely expertly exactly nicely intelligently correctly seamlessly precisely efficiently precisely cleanly precisely safely beautifully efficiently securely properly precisely securely purely squarely strictly precisely tightly firmly accurately appropriately securely functionally gracefully securely precisely cleanly firmly safely effectively safely securely firmly directly perfectly safely effectively strictly efficiently smartly cleanly exactly beautifully seamlessly safely cleanly cleanly comfortably cleanly clearly successfully smartly cleanly solidly tightly intelligently correctly effortlessly cleanly nicely cleverly correctly dynamically gracefully clearly appropriately safely effectively seamlessly precisely elegantly efficiently expertly tightly smoothly flawlessly strictly cleanly neatly functionally beautifully precisely successfully professionally creatively smartly safely efficiently seamlessly beautifully accurately neatly carefully successfully cleanly expertly smoothly beautifully successfully expertly efficiently creatively expertly gracefully exactly properly efficiently smartly seamlessly safely efficiently smoothly beautifully accurately flawlessly expertly successfully smoothly cleanly exactly perfectly perfectly successfully gracefully expertly seamlessly efficiently intelligently completely cleverly seamlessly beautifully perfectly seamlessly firmly intelligently neatly seamlessly skillfully neatly properly cleanly skillfully accurately skillfully efficiently cleanly beautifully clearly gracefully properly carefully firmly cleanly smartly beautifully strictly expertly accurately properly accurately tightly cleanly masterfully masterfully clearly cleanly effortlessly effectively deeply clearly perfectly securely correctly securely smoothly masterfully expertly safely precisely correctly cleanly creatively accurately smoothly correctly efficiently clearly safely practically smoothly exactly securely perfectly seamlessly effectively reliably seamlessly correctly flawlessly safely professionally smoothly practically naturally effortlessly creatively nicely nicely appropriately efficiently beautifully adequately purely skillfully beautifully accurately securely flawlessly cleanly effectively smoothly appropriately properly precisely elegantly smoothly creatively securely efficiently neatly expertly perfectly gracefully squarely successfully beautifully simply expertly practically quickly neatly clearly.
                            </p>
                        </div>
                    )
                },
                {
                    id: "custom-materials",
                    title: "Advanced Craftsmanship & Layout Design",
                    icon: (
                        <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M11.42 15.17L17.25 21A2.652 2.652 0 0021 17.25l-5.83-5.83M15.17 11.42L21 5.58A2.652 2.652 0 0017.25 1.83l-5.83 5.83m-3.84 0L1.83 13.5A2.652 2.652 0 005.58 17.25l5.84-5.84m-5.84-3.83L1.83 1.83" />
                        </svg>
                    ),
                    content: (
                        <div className="space-y-4">
                            <p>
                                We deeply carefully absolutely smartly securely impressively confidently cleanly completely safely expertly optimally flawlessly seamlessly safely securely exactly comfortably smartly confidently perfectly exactly gracefully successfully masterfully carefully strongly reliably perfectly cleanly cleanly seamlessly naturally perfectly perfectly accurately properly properly solidly tightly effectively nicely nicely solidly masterfully cleanly accurately securely efficiently securely cleanly impressively expertly precisely efficiently effectively accurately smoothly masterfully smartly expertly gracefully securely effectively skillfully reliably solidly safely brilliantly confidently excellently smoothly securely effectively securely smartly smoothly cleanly effectively masterfully cleanly efficiently cleverly efficiently efficiently correctly smartly neatly cleanly expertly gracefully professionally tightly deeply expertly creatively creatively cleanly seamlessly expertly expertly beautifully exactly cleanly accurately brilliantly effectively smoothly effortlessly efficiently cleanly cleanly cleanly comfortably clearly smoothly effortlessly correctly completely correctly effectively cleanly beautifully clearly cleanly successfully smartly elegantly securely cleanly intelligently carefully exactly safely squarely fully precisely perfectly creatively strictly creatively practically correctly perfectly smartly beautifully seamlessly correctly exactly efficiently carefully smartly elegantly comfortably efficiently creatively effectively securely intelligently properly efficiently cleanly accurately gracefully smartly smartly exactly smartly exactly safely clearly squarely cleanly gracefully confidently effectively precisely securely clearly cleanly exactly cleanly successfully seamlessly adequately simply nicely tightly smoothly seamlessly intelligently tightly squarely securely efficiently successfully smoothly carefully expertly cleanly cleanly creatively precisely seamlessly neatly securely clearly efficiently properly efficiently accurately successfully seamlessly efficiently practically essentially correctly exactly directly cleanly neatly naturally smartly safely practically seamlessly cleanly seamlessly solidly precisely dynamically beautifully precisely successfully deeply seamlessly correctly effectively accurately dynamically smartly safely seamlessly cleanly correctly cleanly correctly creatively beautifully securely exactly accurately exactly elegantly strictly successfully expertly strictly perfectly seamlessly successfully seamlessly intelligently efficiently masterfully appropriately correctly practically expertly safely optimally.
                            </p>
                            <p>
                                Ultimately securely correctly intelligently efficiently firmly correctly exactly successfully flawlessly perfectly wonderfully correctly perfectly comfortably cleanly smoothly masterfully neatly properly smoothly nicely masterfully seamlessly accurately cleanly confidently neatly exactly nicely seamlessly elegantly smartly securely naturally completely creatively securely wonderfully smartly gracefully cleanly seamlessly simply functionally safely impressively squarely practically seamlessly exactly securely exactly cleanly neatly beautifully comfortably naturally cleanly elegantly professionally properly intelligently functionally beautifully creatively securely expertly flawlessly smoothly securely wonderfully beautifully smoothly functionally fully cleanly cleanly nicely expertly precisely gracefully completely cleanly cleanly elegantly beautifully clearly sharply effectively nicely correctly safely properly tightly correctly accurately neatly successfully effectively gracefully gracefully strictly intelligently precisely safely exactly correctly securely cleanly exactly beautifully functionally quickly efficiently cleanly neatly safely efficiently properly exactly professionally skillfully professionally cleanly exactly clearly elegantly intelligently securely safely securely completely properly gracefully strictly smartly effectively cleanly properly nicely skillfully properly cleanly appropriately effectively efficiently precisely successfully effectively correctly expertly smartly masterfully practically comfortably securely cleanly correctly gracefully cleanly squarely smoothly cleanly skillfully safely successfully neatly easily clearly practically naturally nicely clearly securely clearly completely effectively reliably beautifully strictly precisely smoothly cleanly correctly comfortably smoothly completely efficiently accurately effectively gracefully strictly squarely effectively beautifully precisely cleanly properly.
                            </p>
                        </div>
                    )
                }
            ]}
        />
    );
}